insert into region (name, capital, region) values ('Kachin State', 'Myitkyina', 'North');
insert into region (name, capital, region) values ('Kayah State', 'Loikaw', 'East');
insert into region (name, capital, region) values ('Kayin State', 'Pa-an', 'South');
insert into region (name, capital, region) values ('Chin State', 'Hakha', 'West');
insert into region (name, capital, region) values ('Sagaing Region', 'Sagaing', 'North');
insert into region (name, capital, region) values ('Tanintharyi Region', 'Dawei', 'South');
insert into region (name, capital, region) values ('Naypyidaw Union Territory', 'Naypyidaw', 'Central');
insert into region (name, capital, region) values ('Bago Region', 'Bago', 'Lower');
insert into region (name, capital, region) values ('Magway Region', 'Magwe', 'Central');
insert into region (name, capital, region) values ('Mandalay Region', 'Mandalay', 'Central');
insert into region (name, capital, region) values ('Mon State', 'Mawlamyine', 'South');
insert into region (name, capital, region) values ('Rakhine State', 'Sittwe', 'West');
insert into region (name, capital, region) values ('Yangon Region', 'Yangon', 'Lower');
insert into region (name, capital, region) values ('Shan State', 'Taunggyi', 'East');
insert into region (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'Lower');

insert into township (region_id, name) values (13, 'Ahlon');
insert into township (region_id, name) values (13, 'Bahan');
insert into township (region_id, name) values (13, 'Dagon');
insert into township (region_id, name) values (13, 'Hlaing');
insert into township (region_id, name) values (13, 'Kamayut');
insert into township (region_id, name) values (13, 'Kyauktada');
insert into township (region_id, name) values (13, 'Kyimyindaing');
insert into township (region_id, name) values (13, 'Lanmadaw');
insert into township (region_id, name) values (13, 'Latha');
insert into township (region_id, name) values (13, 'Mayangon');
insert into township (region_id, name) values (13, 'Pabedan');
insert into township (region_id, name) values (13, 'Sanchaung');
insert into township (region_id, name) values (13, 'Seikkan');
insert into township (region_id, name) values (13, 'Botataung');
insert into township (region_id, name) values (13, 'Dagon Seikkan');
insert into township (region_id, name) values (13, 'Dawbon');
insert into township (region_id, name) values (13, 'Mingala Taungnyunt');
insert into township (region_id, name) values (13, 'New Dagon East');
insert into township (region_id, name) values (13, 'New Dagon North');
insert into township (region_id, name) values (13, 'New Dagon South');
insert into township (region_id, name) values (13, 'North Okkalapa');
insert into township (region_id, name) values (13, 'Pazundaung');
insert into township (region_id, name) values (13, 'South Okkalapa');
insert into township (region_id, name) values (13, 'Tamwe');
insert into township (region_id, name) values (13, 'Thaketa');
insert into township (region_id, name) values (13, 'Thingangyun');
insert into township (region_id, name) values (13, 'Yankin');
insert into township (region_id, name) values (13, 'Cocokyun');
insert into township (region_id, name) values (13, 'Dala');
insert into township (region_id, name) values (13, 'Kawhmu');
insert into township (region_id, name) values (13, 'Khayan');
insert into township (region_id, name) values (13, 'Kungyangon');
insert into township (region_id, name) values (13, 'Kyauktan');
insert into township (region_id, name) values (13, 'Seikkyi Kanaungto');
insert into township (region_id, name) values (13, 'Thanlyin');
insert into township (region_id, name) values (13, 'Thongwa');
insert into township (region_id, name) values (13, 'Twante');
insert into township (region_id, name) values (13, 'Hlaingthaya');
insert into township (region_id, name) values (13, 'Hlegu');
insert into township (region_id, name) values (13, 'Hmawbi');
insert into township (region_id, name) values (13, 'Htantabin');
insert into township (region_id, name) values (13, 'Insein');
insert into township (region_id, name) values (13, 'Mingaladon');
insert into township (region_id, name) values (13, 'Shwepyitha');
insert into township (region_id, name) values (13, 'Taikkyi');

