insert into region (name) values ('Ayeyarwady Region');
insert into region (name) values ('Bago Region');
insert into region (name) values ('Chin State');
insert into region (name) values ('Kachin State');
insert into region (name) values ('Kayah State');
insert into region (name) values ('Kayin State');
insert into region (name) values ('Magway Region');
insert into region (name) values ('Mandalay Region');
insert into region (name) values ('Mon State');
insert into region (name) values ('Rakhine State');
insert into region (name) values ('Shan State');
insert into region (name) values ('Sagaing Region');
insert into region (name) values ('Tanintharyi Region');
insert into region (name) values ('Yangon Region');
insert into region (name) values ('Naypyidaw Union Territory');

insert into township (region_id, name) values (14, 'Botataung Township');
insert into township (region_id, name) values (14, 'Dagon Seikkan Township');
insert into township (region_id, name) values (14, 'East Dagon Township');
insert into township (region_id, name) values (14, 'North Dagon Township');
insert into township (region_id, name) values (14, 'North Okkalapa Township');
insert into township (region_id, name) values (14, 'Pazundaung Township');
insert into township (region_id, name) values (14, 'South Dagon Township');
insert into township (region_id, name) values (14, 'South Okkalapa Township');
insert into township (region_id, name) values (14, 'Thingangyun Township');
insert into township (region_id, name) values (14, 'Dawbon Township');
insert into township (region_id, name) values (14, 'Mingala Taungnyunt Township');
insert into township (region_id, name) values (14, 'Tamwe Township');
insert into township (region_id, name) values (14, 'Thaketa Township');
insert into township (region_id, name) values (14, 'Yankin Township');
insert into township (region_id, name) values (14, 'Hlaingthaya Township');
insert into township (region_id, name) values (14, 'Insein Township');
insert into township (region_id, name) values (14, 'Mingaladon Township');
insert into township (region_id, name) values (14, 'Shwepyitha Township');
insert into township (region_id, name) values (14, 'Hlegu Township');
insert into township (region_id, name) values (14, 'Hmawbi Township');
insert into township (region_id, name) values (14, 'Htantabin Township');
insert into township (region_id, name) values (14, 'Taikkyi Township');
insert into township (region_id, name) values (14, 'Dala Township');
insert into township (region_id, name) values (14, 'Seikkyi Kanaungto Township');
insert into township (region_id, name) values (14, 'Cocokyun Township');
insert into township (region_id, name) values (14, 'Kawhmu Township');
insert into township (region_id, name) values (14, 'Kayan Township');
insert into township (region_id, name) values (14, 'Kungyangon Township');
insert into township (region_id, name) values (14, 'Kyauktan Township');
insert into township (region_id, name) values (14, 'Thanlyin Township');
insert into township (region_id, name) values (14, 'Thongwa Township');
insert into township (region_id, name) values (14, 'Twante Township');
insert into township (region_id, name) values (14, 'Tada SubTownship');
insert into township (region_id, name) values (14, 'Ahlon Township');
insert into township (region_id, name) values (14, 'Bahan Township');
insert into township (region_id, name) values (14, 'Dagon Township');
insert into township (region_id, name) values (14, 'Kyauktada Township');
insert into township (region_id, name) values (14, 'Kyimyindaing Township');
insert into township (region_id, name) values (14, 'Lanmadaw Township');
insert into township (region_id, name) values (14, 'Latha Township');
insert into township (region_id, name) values (14, 'Pabedan Township');
insert into township (region_id, name) values (14, 'Sanchaung Township');
insert into township (region_id, name) values (14, 'Seikkan Township');
insert into township (region_id, name) values (14, 'Hlaing Township');
insert into township (region_id, name) values (14, 'Kamayut Township');
insert into township (region_id, name) values (14, 'Mayangon Township');
