insert into region (name, capital, region) values ('Kachin State', 'Myitkyina', 'North');
insert into region (name, capital, region) values ('Kayah State', 'Loikaw', 'East');
insert into region (name, capital, region) values ('Kayin State', 'Pa-an', 'South');
insert into region (name, capital, region) values ('Chin State', 'Hakha', 'West');
insert into region (name, capital, region) values ('Sagaing Region', 'Sagaing', 'North');
insert into region (name, capital, region) values ('Tanintharyi Region', 'Dawei', 'South');
insert into region (name, capital, region) values ('Naypyidaw Union Territory', 'Naypyidaw', 'Central');
insert into region (name, capital, region) values ('Bago Region', 'Bago', 'Lower');
insert into region (name, capital, region) values ('Magway Region', 'Magwe', 'Central');
insert into region (name, capital, region) values ('Mandalay Region', 'Mandalay', 'Central');
insert into region (name, capital, region) values ('Mon State', 'Mawlamyine', 'South');
insert into region (name, capital, region) values ('Rakhine State', 'Sittwe', 'West');
insert into region (name, capital, region) values ('Yangon Region', 'Yangon', 'Lower');
insert into region (name, capital, region) values ('Shan State', 'Taunggyi', 'East');
insert into region (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'Lower');