insert into division (name) values ('Ayeyarwady Region');
insert into division (name) values ('Bago Region');
insert into division (name) values ('Chin State');
insert into division (name) values ('Kachin State');
insert into division (name) values ('Kayah State');
insert into division (name) values ('Kayin State');
insert into division (name) values ('Magway Region');
insert into division (name) values ('Mandalay Region');
insert into division (name) values ('Mon State');
insert into division (name) values ('Rakhine State');
insert into division (name) values ('Shan State');
insert into division (name) values ('Sagaing Region');
insert into division (name) values ('Tanintharyi Region');
insert into division (name) values ('Yangon Region');
insert into division (name) values ('Naypyidaw Union Territory');

insert into township (division_id, name) values (1, 'Hinthada');
insert into township (division_id, name) values (1, 'Lemyethna');
insert into township (division_id, name) values (1, 'Zalun');
insert into township (division_id, name) values (1, 'Ithapyu');
insert into township (division_id, name) values (1, 'Labutta');
insert into township (division_id, name) values (1, 'Mawlamyinegyun');
insert into township (division_id, name) values (1, 'Kyonmanage');
insert into township (division_id, name) values (1, 'Pyinsalu');
insert into township (division_id, name) values (1, 'Danubyu');
insert into township (division_id, name) values (1, 'Ma-ubin');
insert into township (division_id, name) values (1, 'Nyaungdon');
insert into township (division_id, name) values (1, 'Pantanaw');
insert into township (division_id, name) values (1, 'Einme');
insert into township (division_id, name) values (1, 'Myaungmya');
insert into township (division_id, name) values (1, 'Wakema');
insert into township (division_id, name) values (1, 'Shwelaung');
insert into township (division_id, name) values (1, 'Kangyidaunk');
insert into township (division_id, name) values (1, 'Ngapudaw');
insert into township (division_id, name) values (1, 'Pathein');
insert into township (division_id, name) values (1, 'Thabaung');
insert into township (division_id, name) values (1, 'Chaungtha');
insert into township (division_id, name) values (1, 'Hainggyi');
insert into township (division_id, name) values (1, 'Ngayokekaung');
insert into township (division_id, name) values (1, 'Ngwesaung');
insert into township (division_id, name) values (1, 'Bogale');
insert into township (division_id, name) values (1, 'Dedaye');
insert into township (division_id, name) values (1, 'Kyaiklat');
insert into township (division_id, name) values (1, 'Pyapon');
insert into township (division_id, name) values (1, 'Ahmar');
insert into township (division_id, name) values (1, 'Kyaunggon');
insert into township (division_id, name) values (1, 'Kyonpyaw');
insert into township (division_id, name) values (1, 'Yekyi');
insert into township (division_id, name) values (1, 'Ahtaung');
insert into township (division_id, name) values (1, 'Ngathinechaung');
insert into township (division_id, name) values (1, 'Ingapu');
insert into township (division_id, name) values (1, 'Kyangin');
insert into township (division_id, name) values (1, 'Myanaung');
insert into township (division_id, name) values (1, 'Kanaung');

